--liquibase formatted sql

--changeset fkirchmann:1
CREATE TABLE Users (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Deleted BOOLEAN DEFAULT FALSE NOT NULL,
	Deactivated BOOLEAN DEFAULT FALSE NOT NULL,
	First_Name VARCHAR(255) NOT NULL,
	Last_Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	Phone VARCHAR(127),
	Birthday DATE,
	Locale VARCHAR(32) NOT NULL,
	Web_Password_Hash VARCHAR(127),
	Web_Password_Reset_Token VARCHAR(32),
	Wlan_Password VARCHAR(255),
	NAT_IPv4_Assignment_ID INTEGER,
	Room_Assignment_ID INTEGER,
	Permissions BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	UNIQUE (Email),
	INDEX (Email),
	FULLTEXT INDEX Fx_Full_Name (First_Name, Last_Name)
);

CREATE TABLE User_Devices (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	User_ID INTEGER NOT NULL,
	Assigned_From TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Assigned_To TIMESTAMP NULL,
	Name VARCHAR(255) NOT NULL,
	MAC_Address VARCHAR(17) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE User_IPv4_Assignments (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	User_ID INTEGER NOT NULL,
	Assigned_From TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Assigned_To TIMESTAMP NULL,
	IP_ID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE IPv4_Addresses (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Deleted BOOLEAN DEFAULT FALSE NOT NULL,
	Address VARCHAR(15) NOT NULL,
	Current_Assignment_ID INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (Current_Assignment_ID) REFERENCES User_IPv4_Assignments(ID)
);

CREATE TABLE Groups (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255),
	Permissions BIGINT NOT NULL DEFAULT 0,
	Show_Mailing_List BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY (ID),
	UNIQUE (Name)
);

CREATE TABLE User_Groups (
	User_ID INTEGER NOT NULL,
	Group_ID INTEGER NOT NULL,
	CONSTRAINT UQ_UserGroup UNIQUE (User_ID, Group_ID),
	FOREIGN KEY (User_ID) REFERENCES Users(ID),
	FOREIGN KEY (Group_ID) REFERENCES Groups(ID)
);

CREATE TABLE Rooms (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Room_Nr VARCHAR(100) NOT NULL,
	Description TEXT,
	VLAN INT,
	PRIMARY KEY (ID),
	UNIQUE (Room_Nr)
);
	
CREATE TABLE User_Room_Assignments (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	User_ID INTEGER NOT NULL,
	Assigned_From TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Assigned_To TIMESTAMP NULL,
	Expiration TIMESTAMP NULL,
	Room_ID INT NOT NULL,
	Subtenant BOOLEAN DEFAULT FALSE NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (User_ID) REFERENCES Users(ID),
	FOREIGN KEY (Room_ID) REFERENCES Rooms(ID)
);

CREATE TABLE Authentication_Events (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	User_ID INTEGER,
	Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Client_Info VARCHAR(255),
	Auth_Type VARCHAR(32),
	Auth_Result VARCHAR(32),
	PRIMARY KEY (ID),
	INDEX (User_ID),
	INDEX (Time),
	FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

/** 
 * This needs to be added at the end, because the IPv4 and Room assignment
 * tables do not exist yet when the Users table is created
 */
ALTER TABLE Users
	ADD FOREIGN KEY (NAT_IPv4_Assignment_ID) REFERENCES User_IPv4_Assignments(ID),
	ADD FOREIGN KEY (Room_Assignment_ID) REFERENCES User_Room_Assignments(ID);

/* l8r
CREATE TABLE User_Comments (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	User_ID BIGINT NOT NULL,
	Author_ID BIGINT NOT NULL,
	Deleted BOOLEAN DEFAULT FALSE NOT NULL,
	Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Modified TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	Comment TEXT NOT NULL,
	PRIMARY KEY (ID)
);
*/

--changeset fkirchmann:2
ALTER TABLE Users
  ADD COLUMN Matriculation_Number VARCHAR(64) AFTER Birthday,
  ADD COLUMN TIM_Username VARCHAR(64) AFTER Matriculation_Number,
  ADD COLUMN Comments MEDIUMTEXT AFTER TIM_Username;

--changeset fkirchmann:3
ALTER TABLE Users
  ADD COLUMN	NAT_IPv4_Dynamic BOOLEAN DEFAULT TRUE NOT NULL AFTER Wlan_Password;

--changeset fkirchmann:4
ALTER TABLE Users
  ADD COLUMN  Adblock BOOLEAN DEFAULT FALSE NOT NULL AFTER Wlan_Password;
